SET(CROSS_COMPILER_PREFIX /usr/local/arm/4.3.1-eabi-armv6/usr/bin/arm-linux-)

SET(CMAKE_C_COMPILER "${CROSS_COMPILER_PREFIX}gcc")
SET(CMAKE_CXX_COMPILER "${CROSS_COMPILER_PREFIX}g++")
SET(CMAKE_LINKER "${CROSS_COMPILER_PREFIX}ld")
SET(CMAKE_NM "${CROSS_COMPILER_PREFIX}nm")
SET(CMAKE_OBJCOPY "${CROSS_COMPILER_PREFIX}objcopy")
SET(CMAKE_OBJDUMP "${CROSS_COMPILER_PREFIX}objdump")
SET(CMAKE_RANLIB "${CROSS_COMPILER_PREFIX}ranlib")
