######################################################################
# Automatically generated by qmake (2.01a) ? 10? 30 03:37:35 2013
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES = RmObject_UnitTest.cpp

QMAKE_POST_LINK += export QTEST_COLORED=1 && ./$(TARGET)

